In [129]:
import os
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 100)
pd.set_option('display.notebook_repr_html', True)
pd.set_option('display.max_columns', 10)

import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('ggplot')

In [2]:
df = pd.read_csv(os.path.join('../../', 'Downloads', 'storms.csv.gz'))

/Users/mlombardo/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (2,9,10,11,12,16,17,27,28,29,30,35) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
df

,STATE__,BGN_DATE,BGN_TIME,TIME_ZONE,COUNTY,...,LONGITUDE,LATITUDE_E,LONGITUDE_,REMARKS,REFNUM
0,1.0,4/18/1950 0:00:00,130,CST,97.0,...,8812.0,3051.0,8806.0,NaN,1.0
1,1.0,4/18/1950 0:00:00,145,CST,3.0,...,8755.0,0.0,0.0,NaN,2.0
2,1.0,2/20/1951 0:00:00,1600,CST,57.0,...,8742.0,0.0,0.0,NaN,3.0
3,1.0,6/8/1951 0:00:00,900,CST,89.0,...,8626.0,0.0,0.0,NaN,4.0
4,1.0,11/15/1951 0:00:00,1500,CST,43.0,...,8642.0,0.0,0.0,NaN,5.0
...,...,...,...,...,...,...,...,...,...,...,...
902292,56.0,11/30/2011 0:00:00,10:30:00 PM,MST,7.0,...,0.0,0.0,0.0,EPISODE NARRATIVE: A strong cold front moved s...,902293.0
902293,30.0,11/10/2011 0:00:00,02:48:00 PM,MST,9.0,...,0.0,0.0,0.0,EPISODE NARRATIVE: A strong westerly flow alof...,902294.0
902294,2.0,11/8/2011 0:00:00,02:58:00 PM,AKS,213.0,...,0.0,0.0,0.0,EPISODE NARRATIVE: A 960 mb low over the south...,902295.0
902295,2.0,11/9/2011 0:00:00,10:21:00 AM,AKS,202.0,...,0.0,0.0,0.0,EPISODE NARRATIVE: A 960 mb low over the south...,902296.0
902296,1.0,11/28/2011 0:00:00,08:00:00 PM,CST,6.0,...,0.0,0.0,0.0,EPISODE NARRATIVE: An intense upper level low ...,902297.0

In [36]:
df.isnull().sum()

STATE__            0
BGN_DATE           0
BGN_TIME           0
TIME_ZONE          0
COUNTY             0
               ...
LONGITUDE          0
LATITUDE_E        40
LONGITUDE_         0
REMARKS       287433
REFNUM             0
Length: 37, dtype: int64

In [6]:
df.STATE__.unique()

array([  1.,   4.,   5.,   6.,   8.,   9.,  10.,  11.,  12.,  13.,  15.,
        16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,  25.,  26.,
        27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,  36.,  37.,
        38.,  39.,  40.,  41.,  42.,  44.,  45.,  46.,  47.,  48.,  49.,
        50.,  51.,  53.,  54.,  55.,  56.,  72.,   2.,  60.,  66.,  68.,
        78.,  87.,  81.,  84.,  85.,  86.,  88.,  90.,  91.,  95.,  92.,
        93.,  94.,  83.,  89.])

In [11]:
df.REMARKS.value_counts()

                                                                                                                                                                                                                                         24013
Trees down.\r                                                                                                                                                                                                                             1108
Several trees were blown down.\r                                                                                                                                                                                                           567
Trees were downed.\r                                                                                                                                                                                                                       437
Large trees and power lines were blown down.\r                                                                                                                                                                                             421
                                                                                                                                                                                                                                         ...
Heavy rains of five to eight inches caused many of the streets in southeast part of the county to flood.  Frank Road which connects county roads 87 and 95 had to be closed for several hours due to high water.                             1
18 inches of new snow in Big Horn Mountains\r                                                                                                                                                                                                1
EPISODE NARRATIVE: Rapidly-developing thunderstorms quickly strengthened and moved toward the east and southeast while producing severe hail.EVENT NARRATIVE: Estimated nickel-sized hail with a quarter-inch of rain.                       1
Low pressure tracking across the state produced 6 to 12 inches of snow across the region.\r\n\r\n                                                                                                                                            1
EVENT NARRATIVE: Widespread snowfall of 5 to 8 inches occurred. EPISODE NARRATIVE: A low pressure system moved across the Four Corners Area and produced significant snowfall across the mountains and valleys of southwest Colorado.        1
Name: REMARKS, Length: 436905, dtype: int64

In [ ]:
pd.to_datetime(df.BGN_DATE)
df.beginDate = pd.to_datetime(df.BGN_DATE)

In [14]:
df.columns

Index([u'STATE__', u'BGN_DATE', u'BGN_TIME', u'TIME_ZONE', u'COUNTY',
       u'COUNTYNAME', u'STATE', u'EVTYPE', u'BGN_RANGE', u'BGN_AZI',
       u'BGN_LOCATI', u'END_DATE', u'END_TIME', u'COUNTY_END', u'COUNTYENDN',
       u'END_RANGE', u'END_AZI', u'END_LOCATI', u'LENGTH', u'WIDTH', u'F',
       u'MAG', u'FATALITIES', u'INJURIES', u'PROPDMG', u'PROPDMGEXP',
       u'CROPDMG', u'CROPDMGEXP', u'WFO', u'STATEOFFIC', u'ZONENAMES',
       u'LATITUDE', u'LONGITUDE', u'LATITUDE_E', u'LONGITUDE_', u'REMARKS',
       u'REFNUM'],
      dtype='object')

In [69]:
df.COUNTY_END.value_counts()

0.0    902297
Name: COUNTY_END, dtype: int64

In [30]:
df.FATALITIES == True

0         False
1         False
2         False
3         False
4         False
          ...
902292    False
902293    False
902294    False
902295    False
902296    False
Name: FATALITIES, Length: 902297, dtype: bool

In [98]:
df.EVTYPE.value_counts()

HAIL                              288661
TSTM WIND                         219940
THUNDERSTORM WIND                  82563
TORNADO                            60652
FLASH FLOOD                        54277
                                   ...
EXCESSIVE                              1
LANDSLUMP                              1
NORTHERN LIGHTS                        1
HURRICANE EMILY                        1
THUNDERSTORM WINDS/FLASH FLOOD         1
Name: EVTYPE, Length: 985, dtype: int64

In [70]:
for column in df.columns:
    
    if count > 0:
        print '{:10s} {:6d} {:3.0f}%'.format(column, count, 100. * count / n)

NameError: name 'count' is not defined

In [123]:
df[df.FATALITIES > 0][df.INJURIES > 0][df.CROPDMGEXP > 0][df.PROPDMGEXP > 0][['EVTYPE']]

/Users/mlombardo/anaconda/lib/python2.7/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

                         EVTYPE
187909                  TORNADO
188604                  TORNADO
191344             WINTER STORM
192360  WINTER STORM HIGH WINDS
192371            WINTER STORMS
...                         ...
899529                 WILDFIRE
900199              STRONG WIND
900852                  TORNADO
901144                  TORNADO
901756              RIP CURRENT

[555 rows x 1 columns]

In [94]:
df.CROPDMG.unique()

array([  0.00000000e+00,   1.00000000e+01,   5.00000000e+02,
         1.00000000e+00,   4.00000000e+00,   5.00000000e+01,
         5.00000000e+00,   1.50000000e+01,   5.00000000e-01,
         4.00000000e-01,   5.00000000e-02,   2.10000000e+01,
         7.00000000e+00,   1.70000000e+01,   2.60000000e+01,
         2.20000000e+01,   3.00000000e+00,   8.00000000e-01,
         3.90000000e+01,   2.00000000e+01,   3.00000000e+02,
         9.00000000e-01,   4.80000000e+01,   2.00000000e-01,
         1.50000000e+00,   2.50000000e+00,   2.00000000e+00,
         2.00000000e+02,   2.50000000e+01,   1.30000000e+02,
         3.70000000e+01,   9.00000000e+00,   4.50000000e+01,
         1.85000000e+02,   3.50000000e+01,   2.20000000e+00,
         1.20000000e+01,   3.00000000e-01,   9.00000000e+01,
         1.50000000e-01,   1.00000000e+02,   6.60000000e+01,
         1.42000000e+02,   1.10000000e+00,   7.00000000e-01,
         3.30000000e+02,   7.50000000e+02,   6.00000000e+00,
         4.30000000e+01,   6.00000000e+01,   1.50000000e+02,
         1.80000000e+00,   2.50000000e+02,   4.00000000e+01,
         2.00000000e-02,   1.30000000e+00,   3.00000000e+01,
         7.00000000e+01,   1.00000000e-02,   8.00000000e+01,
         3.50000000e+02,   4.00000000e+02,   8.00000000e+00,
         7.50000000e+01,   3.50000000e+00,   6.30000000e+01,
         1.80000000e+01,   2.80000000e-01,   1.00000000e-01,
         1.70000000e+00,   7.50000000e-01,   4.70000000e+00,
         1.60000000e+01,   1.70000000e+02,   6.00000000e+02,
         1.25000000e+02,   6.70000000e+00,   2.10000000e+00,
         6.75000000e+02,   6.00000000e-01,   2.62000000e+02,
         3.32000000e+02,   2.20000000e+02,   5.60000000e+01,
         3.00000000e-02,   3.53000000e+02,   1.77000000e+02,
         3.60000000e+01,   3.73000000e+02,   4.30000000e+02,
         1.60000000e+02,   1.23000000e+02,   1.30000000e+01,
         1.40000000e+02,   3.80000000e+01,   5.20000000e+01,
         2.40000000e-01,   3.20000000e+02,   7.70000000e+00,
         3.70000000e+00,   6.80000000e+00,   1.20000000e+00,
         3.80000000e+02,   6.50000000e+00,   5.60000000e+00,
         7.49000000e+01,   3.41000000e+01,   1.53000000e+01,
         2.40000000e+01,   5.10000000e+00,   2.70000000e+01,
         4.20000000e+01,   8.00000000e+02,   6.50000000e+02,
         2.30000000e+02,   1.05000000e+01,   5.50000000e+01,
         1.58000000e+00,   5.99000000e+00,   1.25000000e+00,
         3.60000000e+00,   5.20000000e+00,   3.25000000e+00,
         5.25000000e+00,   3.22000000e+00,   2.04000000e+02,
         2.40000000e+00,   1.27000000e+02,   7.50000000e+00,
         4.60000000e+01,   3.30000000e+01,   9.00000000e+02,
         1.20000000e+02,   7.00000000e+02,   2.25000000e+00,
         1.98000000e+01,   4.50000000e+00,   1.89680000e+02,
         1.05000000e+00,   8.10000000e+01,   2.25000000e+02,
         3.75000000e+01,   5.40000000e+00,   7.55000000e+00,
         1.40000000e+00,   2.68400000e+01,   5.70000000e+00,
         5.00100000e+02,   9.50000000e+02,   1.57000000e+01,
         1.10000000e+01,   1.75000000e+01,   1.10000000e+02,
         1.12000000e+00,   5.57000000e+01,   1.60000000e+00,
         1.29000000e+01,   2.00400000e+01,   4.65000000e+01,
         6.50000000e+01,   4.80000000e+00,   1.48000000e+00,
         4.36800000e+01,   6.13000000e+02,   1.40000000e+01,
         1.90000000e+01,   3.40000000e+00,   8.50000000e+02,
         4.50000000e+02,   2.40000000e+02,   1.27000000e+00,
         2.80000000e+00,   3.44800000e+01,   1.34000000e+01,
         2.30000000e+01,   1.79600000e+01,   6.37700000e+01,
         9.38000000e+00,   1.24000000e+01,   9.90000000e+00,
         1.21000000e+00,   1.25000000e+01,   7.80000000e+00,
         1.59000000e+02,   2.42000000e+02,   2.80000000e+02,
         1.41000000e+01,   4.20000000e+00,   6.90000000e+00,
         4.97000000e+00,   5.40000000e+02,   7.13000000e+02,
         7.20000000e+00,   5.90000000e+00,   7.36000000e+01,
         7.10000000e+00,   1.02000000e+01,   5.30000000e+00,
         1.71000000e+01,   5.96000000e+02,   7.43000000e+01,
         4.70000000e+02,   6.55000000e+02,   4.60000000e+02,
         1.80000000e+02,   2.90000000e+00,   2.60100000e+02,
         1.45000000e+02,   5.50000000e+00,   3.80000000e+00,
         1.75000000e+00,   9.78000000e+02,   1.37900000e+02,
         7.74800000e+01,   2.80000000e+01,   4.15000000e+01,
         1.90000000e+02,   2.50000000e-01,   6.21000000e+00,
         6.80000000e+01,   1.17000000e+01,   8.50000000e+01,
         1.17000000e+02,   6.40000000e+01,   6.10000000e+00,
         2.60000000e+00,   9.70000000e+01,   3.75000000e+00,
         1.50200000e+02,   1.67900000e+02,   1.35000000e+02,
         1.55000000e+00,   1.15000000e+01,   3.11000000e+00,
         3.88000000e+01,   5.50000000e+02,   3.10000000e+02,
         1.86000000e+02,   8.80000000e+01,   1.05000000e+02,
         1.77000000e+00,   1.49700000e+02,   3.01000000e+02,
         4.66000000e+00,   2.27000000e+01,   3.39000000e+00,
         1.56500000e+01,   1.31010000e+02,   8.80000000e+00,
         2.91000000e+01,   4.75000000e+02,   3.38000000e+02,
         1.23000000e+01,   8.30000000e+00,   1.18000000e+01,
         8.75000000e+02,   2.70000000e+00,   4.65000000e+02,
         1.09920000e+02,   1.54000000e+02,   5.75000000e+02,
         6.60000000e+02,   3.98500000e+01,   4.13600000e+02,
         6.34000000e+01,   2.03000000e+01,   4.91000000e+00,
         6.40000000e+02,   2.26000000e+01,   8.30000000e+01,
         4.16600000e+01,   4.23000000e+01,   4.20000000e+02,
         6.10000000e+01,   8.65000000e+02,   3.06720000e+02,
         2.10000000e+02,   1.35000000e+01,   3.25000000e+02,
         9.75000000e+02,   1.50080000e+02,   1.60960000e+02,
         1.85000000e+00,   1.69600000e+02,   8.08500000e+01,
         8.50000000e+00,   2.90000000e+01,   6.05000000e+02,
         3.99840000e+02,   4.40000000e+01,   3.20000000e+01,
         1.75000000e+02,   1.90000000e+00,   1.02300000e+02,
         5.15000000e+02,   1.56000000e+00,   8.40000000e+00,
         1.51000000e+02,   3.19000000e+01,   1.04500000e+01,
         1.96000000e+00,   6.03000000e+00,   6.85000000e+00,
         7.80000000e+01,   1.65000000e+00,   5.78850000e+02,
         2.50100000e+01,   2.42700000e+01,   2.56000000e+02,
         6.63000000e+00,   5.30000000e+01,   1.15000000e+02,
         4.40000000e+00,   5.10000000e+02,   1.68000000e+02,
         4.80000000e+02,   2.52000000e+01,   6.50500000e+01,
         2.45000000e+01,   4.43000000e+00,   2.75000000e+02,
         8.90000000e+00,   1.32000000e+01,   9.60000000e+00,
         7.81000000e+00,   1.08000000e+01,   1.93000000e+00,
         3.12480000e+02,   2.61000000e+02,   2.70000000e+02,
         4.81000000e+00,   8.55000000e+00,   1.56500000e+02,
         3.35000000e+02,   1.42500000e+01,   1.09200000e+01,
         7.14000000e+00,   1.33000000e+00,   1.19600000e+01,
         2.90000000e+02,   3.10000000e+01,   2.85000000e+02,
         9.32000000e+01,   8.25000000e+01,   8.70000000e+00,
         4.84000000e+01,   2.65000000e+01,   1.52000000e+01,
         2.16000000e+01,   4.60000000e+00,   5.00800000e+02,
         9.90000000e+02,   2.85000000e+00,   5.76000000e+02,
         9.20000000e+02,   8.90000000e+02,   2.16000000e+02,
         1.01500000e+02,   4.90000000e+01,   4.70000000e+01,
         2.19400000e+01,   6.71000000e+02,   8.60000000e+00,
         3.25000000e+01,   4.23000000e+02,   6.65000000e+01,
         2.63600000e+01,   1.80110000e+02,   4.84600000e+01,
         1.01900000e+01,   1.35000000e+00,   1.54690000e+02,
         6.30000000e+02,   4.26500000e+01,   1.47000000e+00,
         4.15000000e+02,   5.80000000e+00,   2.15000000e+00,
         1.51000000e+00,   2.33000000e+00,   2.65000000e+00,
         8.49000000e+00,   1.16800000e+01,   3.45000000e+01,
         1.13900000e+02,   2.23200000e+01,   1.93900000e+02,
         1.19400000e+01,   1.12500000e+02,   1.66000000e+01,
         9.10000000e+00,   4.92400000e+02,   7.70000000e+01,
         1.51000000e+01,   2.30000000e+00,   7.65000000e+01,
         2.22000000e+01,   9.85000000e+02,   4.54000000e+01,
         9.40000000e+00,   4.16000000e+00,   2.63200000e+01,
         5.92000000e+00,   2.47000000e+00,   7.30000000e+01,
         1.55000000e+02,   3.44000000e+02,   6.20000000e+02,
         3.90000000e+02,   3.16000000e+02,   1.53000000e+02,
         5.23000000e+02,   6.70000000e+01,   3.87000000e+02,
         2.43000000e+02,   2.13000000e+02,   6.10000000e+02,
         9.90000000e+01,   6.25000000e+02,   1.33000000e+02,
         1.69000000e+02,   5.88000000e+02,   5.12000000e+02,
         3.75000000e+02,   1.12000000e+02,   4.25000000e+02,
         2.86000000e+02,   2.81000000e+02,   1.65000000e+02,
         1.07000000e+02,   9.10000000e+01,   4.10000000e+01])

In [96]:
len(EVTYPE_2)

40

In [121]:
df.EVTYPE

0            TORNADO
1            TORNADO
2            TORNADO
3            TORNADO
4            TORNADO
             ...
902292     HIGH WIND
902293     HIGH WIND
902294     HIGH WIND
902295      BLIZZARD
902296    HEAVY SNOW
Name: EVTYPE, Length: 902297, dtype: object

In [118]:
df[['EVTYPE','STATE']][(df.FATALITIES > 0) & (df.INJURIES > 0) & (df.CROPDMGEXP > 0)& (df.PROPDMGEXP > 0)].groupby('STATE').count()

       EVTYPE
STATE
AL         56
AM          4
AN          2
AR         28
AS          3
...       ...
VA         12
WA          7
WI          7
WV          3
WY          3

[54 rows x 1 columns]

In [110]:
df[['EVTYPE','STATE']][(df.FATALITIES > 0) & (df.INJURIES > 0) & (df.CROPDMGEXP > 0)& (df.PROPDMGEXP > 0)].groupby('EVTYPE').count()

                         STATE
EVTYPE
AVALANCHE                   11
BLIZZARD                     3
COLD/WIND CHILL              2
DUST STORM                   2
EXCESSIVE HEAT              10
...                        ...
WILDFIRE                    10
WINTER STORM                 6
WINTER STORM HIGH WINDS      1
WINTER STORMS                1
WINTER WEATHER              11

[40 rows x 1 columns]

In [112]:
n = df.shape[0]

for column in df.columns:
    count = df[column].isnull().sum()
    if count > 0:
        print '{:10s} {:6d} {:3.0f}%'.format(column, count, 100. * count / n)

COUNTYNAME   1589   0%
BGN_AZI    547332  61%
BGN_LOCATI 287743  32%
END_DATE   243411  27%
END_TIME   238978  26%
COUNTYENDN 902297 100%
END_AZI    724837  80%
END_LOCATI 499225  55%
F          843563  93%
PROPDMGEXP 465934  52%
CROPDMGEXP 618413  69%
WFO        142069  16%
STATEOFFIC 248769  28%
ZONENAMES  594029  66%
LATITUDE       47   0%
LATITUDE_E     40   0%
REMARKS    287433  32%

In [122]:
df[['EVTYPE','STATE']][(df.FATALITIES > 0) & (df.INJURIES > 0) & (df.CROPDMGEXP > 0)& (df.PROPDMGEXP > 0)].groupby('EVTYPE').count()

                         STATE
EVTYPE
AVALANCHE                   11
BLIZZARD                     3
COLD/WIND CHILL              2
DUST STORM                   2
EXCESSIVE HEAT              10
...                        ...
WILDFIRE                    10
WINTER STORM                 6
WINTER STORM HIGH WINDS      1
WINTER STORMS                1
WINTER WEATHER              11

[40 rows x 1 columns]

In [126]:
df.groupby(['EVTYPE','FATALITIES']).sum()

,,STATE__,COUNTY,BGN_RANGE,COUNTY_END,COUNTYENDN,...,LATITUDE,LONGITUDE,LATITUDE_E,LONGITUDE_,REFNUM
EVTYPE,FATALITIES,,,,,,,,,,,
HIGH SURF ADVISORY,0.0,60.0,2.0,0.0,0.0,NaN,...,0.0,0.0,0.0,0.0,448421.0
COASTAL FLOOD,0.0,34.0,17.0,0.0,0.0,NaN,...,0.0,0.0,0.0,0.0,265763.0
FLASH FLOOD,0.0,48.0,201.0,0.0,0.0,NaN,...,0.0,0.0,0.0,0.0,408333.0
LIGHTNING,0.0,4.0,25.0,0.0,0.0,NaN,...,0.0,0.0,0.0,0.0,311043.0
TSTM WIND,0.0,56.0,414.0,0.0,0.0,NaN,...,0.0,0.0,0.0,0.0,1379765.0
...,...,...,...,...,...,...,...,...,...,...,...,...
blowing snow,1.0,38.0,23.0,0.0,0.0,NaN,...,0.0,0.0,0.0,0.0,298038.0
coastal flooding,0.0,96.0,64.0,0.0,0.0,NaN,...,0.0,0.0,0.0,0.0,555389.0
gradient wind,0.0,96.0,464.0,0.0,0.0,NaN,...,0.0,0.0,0.0,0.0,608065.0
small hail,0.0,222.0,95.0,0.0,0.0,NaN,...,0.0,0.0,0.0,0.0,1367923.0
wet micoburst,0.0,41.0,19.0,10.0,0.0,NaN,...,0.0,0.0,0.0,0.0,271526.0

In [127]:
#
df[['EVTYPE','FATALITIES']].groupby('EVTYPE').count().sort_values('FATALITIES',ascending=False).tail(100)

                       FATALITIES
EVTYPE
SUMMARY OF MARCH 27             1
SUMMARY OF MARCH 29             1
SNOW SLEET                      1
SNOW AND WIND                   1
SNOW AND ICE STORM              1
...                           ...
LACK OF SNOW                    1
LAKE FLOOD                      1
LANDSLIDE/URBAN FLOOD           1
LANDSLUMP                       1
wet micoburst                   1

[100 rows x 1 columns]

In [138]:
df[['EVTYPE','FATALITIES']].groupby('EVTYPE').sum().sort_values('FATALITIES', ascending=False)

                                FATALITIES
EVTYPE
TORNADO                             5633.0
EXCESSIVE HEAT                      1903.0
FLASH FLOOD                          978.0
HEAT                                 937.0
LIGHTNING                            816.0
TSTM WIND                            504.0
FLOOD                                470.0
RIP CURRENT                          368.0
HIGH WIND                            248.0
AVALANCHE                            224.0
WINTER STORM                         206.0
RIP CURRENTS                         204.0
HEAT WAVE                            172.0
EXTREME COLD                         160.0
THUNDERSTORM WIND                    133.0
HEAVY SNOW                           127.0
EXTREME COLD/WIND CHILL              125.0
STRONG WIND                          103.0
HIGH SURF                            101.0
BLIZZARD                             101.0
HEAVY RAIN                            98.0
EXTREME HEAT                          96.0
COLD/WIND CHILL                       95.0
ICE STORM                             89.0
WILDFIRE                              75.0
HURRICANE/TYPHOON                     64.0
THUNDERSTORM WINDS                    64.0
FOG                                   62.0
HURRICANE                             61.0
TROPICAL STORM                        58.0
HEAVY SURF/HIGH SURF                  42.0
LANDSLIDE                             38.0
COLD                                  35.0
HIGH WINDS                            35.0
TSUNAMI                               33.0
WINTER WEATHER                        33.0
UNSEASONABLY WARM AND DRY             29.0
WINTER WEATHER/MIX                    28.0
URBAN/SML STREAM FLD                  28.0
TORNADOES, TSTM WIND, HAIL            25.0
WIND                                  23.0
DUST STORM                            22.0
FLASH FLOODING                        19.0
DENSE FOG                             18.0
RECORD/EXCESSIVE HEAT                 17.0
FLOOD/FLASH FLOOD                     17.0
EXTREME WINDCHILL                     17.0
HAIL                                  15.0
MARINE STRONG WIND                    14.0
COLD AND SNOW                         14.0
...                                    ...
HIGHWAY FLOODING                       0.0
HOT PATTERN                            0.0
HOT SPELL                              0.0
HOT WEATHER                            0.0
HOT/DRY PATTERN                        0.0
HURRICANE EMILY                        0.0
HURRICANE GORDON                       0.0
HURRICANE-GENERATED SWELLS             0.0
HVY RAIN                               0.0
Hail(0.75)                             0.0
Heat Wave                              0.0
Heatburst                              0.0
Heavy Precipitation                    0.0
Heavy Rain                             0.0
Heavy Rain and Wind                    0.0
Heavy Rain/High Surf                   0.0
Heavy rain                             0.0
Heavy snow shower                      0.0
High Wind                              0.0
Hot and Dry                            0.0
Hurricane Edouard                      0.0
ICE AND SNOW                           0.0
HIGH WINDS/FLOODING                    0.0
HIGH WINDS/COASTAL FLOOD               0.0
HIGH WIND 70                           0.0
HIGH WINDS/                            0.0
HIGH WIND AND HEAVY SNOW               0.0
HIGH WIND AND HIGH TIDES               0.0
HIGH WIND DAMAGE                       0.0
HIGH WIND/ BLIZZARD                    0.0
HIGH WIND/BLIZZARD                     0.0
HIGH WIND/BLIZZARD/FREEZING RA         0.0
HIGH WIND/HEAVY SNOW                   0.0
HIGH WIND/LOW WIND CHILL               0.0
HIGH WIND/WIND CHILL                   0.0
HIGH WIND/WIND CHILL/BLIZZARD          0.0
HIGH WINDS 55                          0.0
HIGH WINDS 57                          0.0
HIGH WINDS 58                          0.0
HIGH WINDS 63                          0.0
HIGH WINDS 66                          0.0
HIGH WINDS 67                          0.0
HIGH WINDS 73                          0.0
HIGH WINDS 76                          0.0
HIGH WINDS 80                          0.0
HIGH WINDS 82                          0.0
HIGH WINDS AND WIND CHILL              0.0
HIGH WINDS DUST STORM                  0.0
HIGH WINDS HEAVY RAINS                 0.0
wet micoburst                          0.0

[985 rows x 1 columns]

In [140]:
df[['EVTYPE','INJURIES']].groupby('EVTYPE').sum().sort_values('INJURIES', ascending=False)

                                INJURIES
EVTYPE
TORNADO                          91346.0
TSTM WIND                         6957.0
FLOOD                             6789.0
EXCESSIVE HEAT                    6525.0
LIGHTNING                         5230.0
HEAT                              2100.0
ICE STORM                         1975.0
FLASH FLOOD                       1777.0
THUNDERSTORM WIND                 1488.0
HAIL                              1361.0
WINTER STORM                      1321.0
HURRICANE/TYPHOON                 1275.0
HIGH WIND                         1137.0
HEAVY SNOW                        1021.0
WILDFIRE                           911.0
THUNDERSTORM WINDS                 908.0
BLIZZARD                           805.0
FOG                                734.0
WILD/FOREST FIRE                   545.0
DUST STORM                         440.0
WINTER WEATHER                     398.0
DENSE FOG                          342.0
TROPICAL STORM                     340.0
HEAT WAVE                          309.0
HIGH WINDS                         302.0
RIP CURRENTS                       297.0
STRONG WIND                        280.0
HEAVY RAIN                         251.0
RIP CURRENT                        232.0
EXTREME COLD                       231.0
GLAZE                              216.0
AVALANCHE                          170.0
EXTREME HEAT                       155.0
HIGH SURF                          152.0
WILD FIRES                         150.0
ICE                                137.0
TSUNAMI                            129.0
TSTM WIND/HAIL                      95.0
WIND                                86.0
URBAN/SML STREAM FLD                79.0
WINTRY MIX                          77.0
WINTER WEATHER/MIX                  72.0
Heat Wave                           70.0
WINTER WEATHER MIX                  68.0
LANDSLIDE                           52.0
RECORD HEAT                         50.0
COLD                                48.0
HEAVY SURF/HIGH SURF                48.0
HURRICANE                           46.0
TROPICAL STORM GORDON               43.0
...                                  ...
HIGH WINDS HEAVY RAINS               0.0
HIGH WINDS/                          0.0
HIGH WINDS/COASTAL FLOOD             0.0
HIGH WINDS/FLOODING                  0.0
HIGH WINDS/HEAVY RAIN                0.0
HIGHWAY FLOODING                     0.0
HOT PATTERN                          0.0
HOT SPELL                            0.0
HOT WEATHER                          0.0
HURRICANE FELIX                      0.0
HIGH SWELLS                          0.0
HURRICANE GORDON                     0.0
HURRICANE OPAL/HIGH WINDS            0.0
HVY RAIN                             0.0
HYPERTHERMIA/EXPOSURE                0.0
HYPOTHERMIA                          0.0
HYPOTHERMIA/EXPOSURE                 0.0
Hail(0.75)                           0.0
Heatburst                            0.0
Heavy Precipitation                  0.0
Heavy Rain                           0.0
Heavy Rain and Wind                  0.0
HIGH WINDS 82                        0.0
HIGH WINDS 80                        0.0
HIGH WINDS 76                        0.0
HIGH WINDS 73                        0.0
HIGH TEMPERATURE RECORD              0.0
HIGH TIDES                           0.0
HIGH WATER                           0.0
HIGH WAVES                           0.0
HIGH WIND (G40)                      0.0
HIGH WIND 63                         0.0
HIGH WIND 70                         0.0
HIGH WIND AND HEAVY SNOW             0.0
HIGH WIND AND HIGH TIDES             0.0
HIGH WIND DAMAGE                     0.0
HIGH WIND/ BLIZZARD                  0.0
HIGH WIND/BLIZZARD                   0.0
HIGH WIND/BLIZZARD/FREEZING RA       0.0
HIGH WIND/LOW WIND CHILL             0.0
HIGH WIND/SEAS                       0.0
HIGH WIND/WIND CHILL                 0.0
HIGH WIND/WIND CHILL/BLIZZARD        0.0
HIGH WINDS 55                        0.0
HIGH WINDS 57                        0.0
HIGH WINDS 58                        0.0
HIGH WINDS 63                        0.0
HIGH WINDS 66                        0.0
HIGH WINDS 67                        0.0
wet micoburst                        0.0

[985 rows x 1 columns]

In [143]:
df[['EVTYPE','STATE']].groupby('STATE').count().sort_values('EVTYPE',ascending = False)

       EVTYPE
STATE
TX      83728
KS      53440
OK      46802
MO      35648
IA      31069
NE      30271
IL      28488
AR      27102
NC      25351
GA      25259
OH      24922
MN      23609
AL      22739
PA      22226
MS      22192
FL      22124
KY      22092
SD      21727
TN      21721
IN      21506
VA      21189
NY      21058
CO      20473
WI      19781
MI      17910
LA      17323
SC      17126
MT      14695
ND      14632
CA      10780
WV       9099
MD       8185
NJ       8075
WY       7332
NM       7129
AZ       6156
MA       5652
GM       5337
OR       4821
ID       4767
ME       4524
AK       4391
UT       4135
VT       3871
WA       3312
CT       3294
AN       3250
NV       3139
NH       3022
PR       3015
HI       2547
DE       1913
AM       1879
LE       1526
LM       1347
RI        839
LH        654
DC        437
VI        338
GU        306
LC        274
LS        262
AS        257
PZ         96
LO         70
PH         28
PK         23
SL          7
XX          2
ST          1
MH          1
PM          1

In [141]:
df[['EVTYPE']].count()

EVTYPE    902297
dtype: int64

In [156]:
df[['EVTYPE','STATE']].groupby('STATE').count().sort_values('EVTYPE',ascending = False)

       EVTYPE
STATE
TX      83728
KS      53440
OK      46802
MO      35648
IA      31069
NE      30271
IL      28488
AR      27102
NC      25351
GA      25259
OH      24922
MN      23609
AL      22739
PA      22226
MS      22192
FL      22124
KY      22092
SD      21727
TN      21721
IN      21506
VA      21189
NY      21058
CO      20473
WI      19781
MI      17910
LA      17323
SC      17126
MT      14695
ND      14632
CA      10780
WV       9099
MD       8185
NJ       8075
WY       7332
NM       7129
AZ       6156
MA       5652
GM       5337
OR       4821
ID       4767
ME       4524
AK       4391
UT       4135
VT       3871
WA       3312
CT       3294
AN       3250
NV       3139
NH       3022
PR       3015
HI       2547
DE       1913
AM       1879
LE       1526
LM       1347
RI        839
LH        654
DC        437
VI        338
GU        306
LC        274
LS        262
AS        257
PZ         96
LO         70
PH         28
PK         23
SL          7
XX          2
ST          1
MH          1
PM          1

In [150]:
df[['EVTYPE','TIME_ZONE']].groupby('TIME_ZONE').count().sort_values('EVTYPE',ascending = False)

           EVTYPE
TIME_ZONE
CST        547493
EST        245558
MST         68390
PST         28302
AST          6360
HST          2563
AKS          1553
CDT           692
EDT           569
SST           505
PDT           154
MDT            99
GST            32
UNK             9
UTC             4
CSt             4
ADT             3
ESt             2
SCT             2
ESY             1
CSC             1
GMT             1

In [155]:
(df[['FATALITIES','TIME_ZONE']].groupby('TIME_ZONE').count() / df[['FATALITIES']].count() * 100).sort_values('FATALITIES',ascending = False)

           FATALITIES
TIME_ZONE
CST         60.677693
EST         27.214764
MST          7.579544
PST          3.136661
AST          0.704868
HST          0.284053
AKS          0.172116
CDT          0.076693
EDT          0.063061
SST          0.055968
PDT          0.017068
MDT          0.010972
GST          0.003547
UNK          0.000997
UTC          0.000443
CSt          0.000443
ADT          0.000332
ESt          0.000222
SCT          0.000222
ESY          0.000111
CSC          0.000111
GMT          0.000111

In [149]:
(df[['INJURIES','TIME_ZONE']].groupby('TIME_ZONE').count() / df[['INJURIES']].count() * 100).sort_values('INJURIES',ascending = False)

            INJURIES
TIME_ZONE
CST        60.677693
EST        27.214764
MST         7.579544
PST         3.136661
AST         0.704868
HST         0.284053
AKS         0.172116
CDT         0.076693
EDT         0.063061
SST         0.055968
PDT         0.017068
MDT         0.010972
GST         0.003547
UNK         0.000997
UTC         0.000443
CSt         0.000443
ADT         0.000332
ESt         0.000222
SCT         0.000222
ESY         0.000111
CSC         0.000111
GMT         0.000111

In [175]:
d = df.groupby(['EVTYPE','FATALITIES']).sum()

In [ ]:
df[ ['EVTYPE', 'FATALITIES'] ].plot(kind = 'hist', figsize = (8, 8))

In [47]:
et_fat = df[['EVTYPE','FATALITIES']].groupby('EVTYPE').sum().sort_values('FATALITIES',ascending=False)

In [50]:
et_fat.plot.bar(x = EVTYPE)

NameError: name 'EVTYPE' is not defined

In [51]:
dd = df[['FATALITIES','EVTYPE','STATE']].groupby(['EVTYPE','STATE']).sum().sort_values('FATALITIES',ascending=False)
dd

                                      FATALITIES
EVTYPE                         STATE
HEAT                           IL          653.0
TORNADO                        AL          617.0
                               TX          538.0
                               MS          450.0
                               MO          388.0
                               AR          379.0
                               TN          368.0
EXCESSIVE HEAT                 PA          359.0
                               IL          330.0
TORNADO                        OK          296.0
EXCESSIVE HEAT                 TX          269.0
TORNADO                        IN          252.0
                               MI          243.0
                               KS          236.0
                               IL          203.0
                               OH          191.0
EXCESSIVE HEAT                 MO          190.0
TORNADO                        GA          180.0
FLASH FLOOD                    TX          177.0
RIP CURRENT                    FL          172.0
TORNADO                        FL          161.0
                               LA          153.0
                               NC          126.0
                               KY          125.0
LIGHTNING                      FL          123.0
EXCESSIVE HEAT                 CA          110.0
TORNADO                        MA          108.0
HEAT WAVE                      PA          107.0
RIP CURRENTS                   FL           99.0
TORNADO                        MN           99.0
                               WI           96.0
EXCESSIVE HEAT                 NY           93.0
                               MD           88.0
TORNADO                        PA           82.0
                               IA           81.0
FLASH FLOOD                    MO           72.0
EXTREME HEAT                   WI           67.0
EXTREME COLD/WIND CHILL        IL           64.0
EXCESSIVE HEAT                 OK           63.0
FLASH FLOOD                    AZ           62.0
TORNADO                        SC           59.0
LIGHTNING                      TX           57.0
EXCESSIVE HEAT                 AZ           55.0
                               LA           55.0
TORNADO                        NE           54.0
HEAT                           NV           54.0
COLD/WIND CHILL                IL           51.0
FLASH FLOOD                    PA           50.0
                               AR           49.0
FLOOD                          TX           49.0
...                                          ...
HEAVY RAIN/SNOW                ID            0.0
HEAVY RAIN/URBAN FLOOD         PR            0.0
HEAVY RAIN/WIND                MD            0.0
                               NJ            0.0
                               PA            0.0
HEAVY RAIN; URBAN FLOOD WINDS; OR            0.0
HEAVY RAINFALL                 ME            0.0
                               NH            0.0
                               TX            0.0
HEAVY RAINS                    ID            0.0
HEAVY RAIN                     MA            0.0
HEAVY RAINS                    ME            0.0
                               ND            0.0
                               PR            0.0
                               SC            0.0
                               SD            0.0
                               WI            0.0
HEAVY RAINS/FLOODING           SC            0.0
HEAVY SHOWER                   PR            0.0
HEAVY SHOWERS                  PR            0.0
HEAVY SNOW                     AL            0.0
                               AR            0.0
HEAVY RAIN/SEVERE WEATHER      LA            0.0
HEAVY RAIN/MUDSLIDES/FLOOD     SC            0.0
HEAVY RAIN/LIGHTNING           AL            0.0
HEAVY RAIN/FLOODING            SD            0.0
HEAVY RAIN                     ME            0.0
                               MI            0.0
                               MN            0.0
                               MS            0.0
                               MT            0.0
                               NC            0.0
                               NE            0.0
                               NH            0.0
                               NV            0.0
                               NY            0.0
                               OK            0.0
                               OR            0.0
                               RI            0.0
                               SD            0.0
                               UT            0.0
                               VA            0.0
                               VI            0.0
                               VT            0.0
                               WI            0.0
                               WY            0.0
HEAVY RAIN AND FLOOD           NH            0.0
HEAVY RAIN EFFECTS             NC            0.0
HEAVY RAIN/FLOODING            CO            0.0
wet micoburst                  OR            0.0

[4258 rows x 1 columns]